# =============================================================================
# HPA - billing-hpa
# Servicio: Billing Service
# =============================================================================
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: siga-billing-hpa
  namespace: siga
  labels:
    app: siga-billing
    project: siga
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: siga-billing
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
