-- =============================================================================
-- Script de Creación de Tablas para el Proyecto SIGA
-- =============================================================================

-- ========= TABLAS DE CATÁLOGO Y CONFIGURACIÓN =========

CREATE TABLE CATEGORIAS (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(100) NOT NULL UNIQUE,
    creado_en   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE LOCALES (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(100) NOT NULL,
    direccion   VARCHAR2(255),
    creado_en   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE USUARIOS (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(100) NOT NULL,
    email       VARCHAR2(100) NOT NULL UNIQUE,
    rol         VARCHAR2(20) NOT NULL CHECK (rol IN ('ADMINISTRADOR', 'VENDEDOR')),
    local_id    NUMBER,
    creado_en   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_usuarios_local FOREIGN KEY (local_id) REFERENCES LOCALES(id)
);

-- ========= TABLAS MAESTRAS =========

CREATE TABLE PRODUCTOS (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku             VARCHAR2(50) NOT NULL UNIQUE,
    nombre          VARCHAR2(255) NOT NULL,
    costo           DECIMAL(10, 2) NOT NULL,
    precio_venta    DECIMAL(10, 2) NOT NULL,
    categoria_id    NUMBER NOT NULL,
    creado_en       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_productos_categoria FOREIGN KEY (categoria_id) REFERENCES CATEGORIAS(id)
);

-- ========= TABLAS OPERACIONALES =========

CREATE TABLE STOCK (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id     NUMBER NOT NULL,
    local_id        NUMBER NOT NULL,
    cantidad        NUMBER NOT NULL CHECK (cantidad >= 0),
    umbral_alerta   NUMBER DEFAULT 0 NOT NULL,
    actualizado_en  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_stock_producto_local UNIQUE (producto_id, local_id),
    CONSTRAINT fk_stock_producto FOREIGN KEY (producto_id) REFERENCES PRODUCTOS(id),
    CONSTRAINT fk_stock_local FOREIGN KEY (local_id) REFERENCES LOCALES(id)
);

CREATE TABLE VENTAS (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id        NUMBER NOT NULL,
    usuario_id      NUMBER NOT NULL,
    fecha_hora      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    metodo_pago     VARCHAR2(50) NOT NULL CHECK (metodo_pago IN ('EFECTIVO', 'TARJETA', 'TRANSFERENCIA')),
    total           DECIMAL(10, 2) NOT NULL,
    CONSTRAINT fk_ventas_local FOREIGN KEY (local_id) REFERENCES LOCALES(id),
    CONSTRAINT fk_ventas_usuario FOREIGN KEY (usuario_id) REFERENCES USUARIOS(id)
);

CREATE TABLE DETALLES_VENTA (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id            NUMBER NOT NULL,
    producto_id         NUMBER NOT NULL,
    cantidad            NUMBER NOT NULL CHECK (cantidad > 0),
    precio_unitario     DECIMAL(10, 2) NOT NULL,
    CONSTRAINT fk_detalles_venta FOREIGN KEY (venta_id) REFERENCES VENTAS(id),
    CONSTRAINT fk_detalles_producto FOREIGN KEY (producto_id) REFERENCES PRODUCTOS(id)
);

CREATE TABLE MOVIMIENTOS (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id     NUMBER NOT NULL,
    local_id        NUMBER NOT NULL,
    usuario_id      NUMBER,
    tipo            VARCHAR2(20) NOT NULL CHECK (tipo IN ('COMPRA', 'VENTA', 'MERMA', 'AJUSTE_INICIAL', 'AJUSTE_MANUAL')),
    cantidad        NUMBER NOT NULL,
    fecha_hora      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    nota            VARCHAR2(255),
    CONSTRAINT fk_movimientos_producto FOREIGN KEY (producto_id) REFERENCES PRODUCTOS(id),
    CONSTRAINT fk_movimientos_local FOREIGN KEY (local_id) REFERENCES LOCALES(id),
    CONSTRAINT fk_movimientos_usuario FOREIGN KEY (usuario_id) REFERENCES USUARIOS(id)
);

CREATE TABLE ALERTAS (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id        NUMBER NOT NULL,
    tipo            VARCHAR2(50) NOT NULL, -- Ej: 'BAJO_STOCK_PREDICHO', 'BAJO_STOCK_UMBRAL'
    mensaje         VARCHAR2(255) NOT NULL,
    atendida        CHAR(1) DEFAULT 'N' NOT NULL CHECK (atendida IN ('S', 'N')),
    fecha_hora      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_alertas_stock FOREIGN KEY (stock_id) REFERENCES STOCK(id)
);

-- =============================================================================
-- Creación de Índices para optimizar consultas comunes
-- =============================================================================
CREATE INDEX idx_productos_nombre ON PRODUCTOS(nombre);
CREATE INDEX idx_movimientos_fecha ON MOVIMIENTOS(fecha_hora);
CREATE INDEX idx_ventas_fecha ON VENTAS(fecha_hora);