server:
  port: 8080

spring:
  application:
    name: siga-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
eureka:
  instance:
    hostname: siga-gateway
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://siga-eureka:8761/eureka/}
