-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS agent.conversations
(
    id serial NOT NULL,
    tenant_id integer NOT NULL,
    user_id integer NOT NULL,
    session_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    context jsonb,
    metadata jsonb,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT conversations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS agent.documents
(
    id serial NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    embedding vector(1536),
    source character varying(100) COLLATE pg_catalog."default",
    tenant_id integer NOT NULL,
    indexed_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT documents_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS agent.intent_logs
(
    id serial NOT NULL,
    tenant_id integer NOT NULL,
    user_id integer NOT NULL,
    query_text text COLLATE pg_catalog."default" NOT NULL,
    detected_intent character varying(50) COLLATE pg_catalog."default",
    confidence_score numeric(3, 2),
    raw_response jsonb,
    metadata jsonb,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT intent_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS agent.intent_permissions
(
    id serial NOT NULL,
    plan_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    intent character varying(50) COLLATE pg_catalog."default" NOT NULL,
    is_allowed boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT intent_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT uq_intent_plan UNIQUE (plan_name, intent)
);

CREATE TABLE IF NOT EXISTS agent.pending_actions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id integer NOT NULL,
    user_id integer NOT NULL,
    intent character varying(50) COLLATE pg_catalog."default" NOT NULL,
    action_data jsonb NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    expires_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at timestamp without time zone,
    CONSTRAINT pending_actions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS auth.permissions
(
    id serial NOT NULL,
    code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    category character varying(50) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT permissions_pkey PRIMARY KEY (id),
    CONSTRAINT permissions_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS auth.role_permissions
(
    role character varying(20) COLLATE pg_catalog."default" NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (role, permission_id)
);

CREATE TABLE IF NOT EXISTS auth.user_permissions
(
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    assigned_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by integer,
    CONSTRAINT user_permissions_pkey PRIMARY KEY (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS auth.user_stores
(
    user_id integer NOT NULL,
    store_id integer NOT NULL,
    assigned_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_stores_pkey PRIMARY KEY (user_id, store_id)
);

CREATE TABLE IF NOT EXISTS auth.users
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default",
    role character varying(20) COLLATE pg_catalog."default" NOT NULL,
    commercial_user_id integer,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS commercial.customers
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default",
    tax_id character varying(20) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    company_name character varying(255) COLLATE pg_catalog."default",
    role character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'customer'::character varying,
    is_on_trial boolean NOT NULL DEFAULT true,
    trial_start_at timestamp without time zone,
    trial_end_at timestamp without time zone,
    plan_id integer,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT customers_pkey PRIMARY KEY (id),
    CONSTRAINT customers_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS commercial.invoices
(
    id serial NOT NULL,
    invoice_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    customer_id integer NOT NULL,
    customer_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    customer_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    plan_id integer NOT NULL,
    plan_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    price_clp numeric(12, 2),
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_at timestamp without time zone,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PAID'::character varying,
    payment_method character varying(100) COLLATE pg_catalog."default",
    last_4_digits character varying(4) COLLATE pg_catalog."default",
    subscription_id integer,
    payment_id integer,
    tax_amount numeric(10, 2),
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_date timestamp(6) with time zone,
    price_uf numeric(10, 2) NOT NULL,
    purchased_at timestamp(6) with time zone NOT NULL,
    tax numeric(10, 2),
    unit character varying(10) COLLATE pg_catalog."default" NOT NULL,
    user_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id integer NOT NULL,
    user_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT invoices_pkey PRIMARY KEY (id),
    CONSTRAINT invoices_invoice_number_key UNIQUE (invoice_number)
);

CREATE TABLE IF NOT EXISTS commercial.payments
(
    id serial NOT NULL,
    subscription_id integer NOT NULL,
    customer_id integer NOT NULL,
    amount numeric(10, 2) NOT NULL,
    payment_method character varying(50) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    reference character varying(100) COLLATE pg_catalog."default",
    paid_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS commercial.plans
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    store_limit integer NOT NULL DEFAULT 1,
    user_limit integer NOT NULL DEFAULT 3,
    product_limit integer,
    monthly_price numeric(10, 2) NOT NULL,
    annual_price numeric(10, 2),
    sort_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT plans_pkey PRIMARY KEY (id),
    CONSTRAINT plans_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS commercial.subscriptions
(
    id serial NOT NULL,
    customer_id integer NOT NULL,
    plan_id integer NOT NULL,
    period character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'MONTHLY'::character varying,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'ACTIVE'::character varying,
    start_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_at timestamp without time zone,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT subscriptions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventory.alerts
(
    id serial NOT NULL,
    type character varying(30) COLLATE pg_catalog."default" NOT NULL,
    product_id integer,
    store_id integer,
    message text COLLATE pg_catalog."default" NOT NULL,
    is_read boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT alerts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventory.categories
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    commercial_user_id integer NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT uq_categories_name_commercial UNIQUE (name, commercial_user_id)
);

CREATE TABLE IF NOT EXISTS inventory.movements
(
    id serial NOT NULL,
    product_id integer NOT NULL,
    store_id integer NOT NULL,
    type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    previous_quantity integer NOT NULL,
    new_quantity integer NOT NULL,
    quantity integer NOT NULL,
    user_id integer,
    sale_id integer,
    observations text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT movements_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventory.products
(
    id serial NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    category_id integer,
    barcode character varying(50) COLLATE pg_catalog."default",
    unit_price numeric(10, 2),
    commercial_user_id integer NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT products_barcode_key UNIQUE (barcode)
);

CREATE TABLE IF NOT EXISTS inventory.stock
(
    id serial NOT NULL,
    product_id integer NOT NULL,
    store_id integer NOT NULL,
    quantity integer NOT NULL DEFAULT 0,
    minimum_quantity integer NOT NULL DEFAULT 0,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT stock_pkey PRIMARY KEY (id),
    CONSTRAINT ukr06971eqh51nwl5rr65ns5shu UNIQUE (product_id, store_id),
    CONSTRAINT uq_stock_product_store UNIQUE (product_id, store_id)
);

CREATE TABLE IF NOT EXISTS inventory.stores
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default",
    city character varying(100) COLLATE pg_catalog."default",
    commercial_user_id integer NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT stores_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sales.cash_shifts
(
    id serial NOT NULL,
    store_id integer NOT NULL,
    user_id integer NOT NULL,
    opened_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at timestamp without time zone,
    initial_amount numeric(10, 2) NOT NULL,
    final_amount numeric(10, 2),
    counted_amount numeric(10, 2),
    status character varying(10) COLLATE pg_catalog."default" NOT NULL DEFAULT 'OPEN'::character varying,
    actual_balance numeric(10, 2),
    closing_balance numeric(10, 2),
    opening_balance numeric(10, 2) NOT NULL,
    CONSTRAINT cash_shifts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sales.payment_methods
(
    id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT payment_methods_pkey PRIMARY KEY (id),
    CONSTRAINT payment_methods_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS sales.pos_cart
(
    id serial NOT NULL,
    sale_id integer,
    product_id integer NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    unit_price numeric(10, 2) NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    store_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT pos_cart_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sales.pos_transactions
(
    id serial NOT NULL,
    sale_id integer NOT NULL,
    shift_id integer NOT NULL,
    payment_method_id integer NOT NULL,
    amount numeric(10, 2) NOT NULL,
    last_4_digits character varying(4) COLLATE pg_catalog."default",
    payment_reference character varying(100) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cash_shift_id integer NOT NULL,
    change numeric(10, 2),
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pos_transactions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sales.sale_items
(
    id serial NOT NULL,
    sale_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10, 2) NOT NULL,
    subtotal numeric(10, 2) NOT NULL,
    CONSTRAINT sale_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sales.sales
(
    id serial NOT NULL,
    store_id integer NOT NULL,
    user_id integer,
    total numeric(10, 2) NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'COMPLETED'::character varying,
    observations text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    commercial_user_id integer,
    CONSTRAINT sales_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS auth.role_permissions
    ADD CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id)
    REFERENCES auth.permissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_role_permissions_permission
    ON auth.role_permissions(permission_id);


ALTER TABLE IF EXISTS auth.user_permissions
    ADD CONSTRAINT fk_user_perm_permission FOREIGN KEY (permission_id)
    REFERENCES auth.permissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS auth.user_permissions
    ADD CONSTRAINT fk_user_perm_user FOREIGN KEY (user_id)
    REFERENCES auth.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS auth.user_stores
    ADD CONSTRAINT fk_user_store_store FOREIGN KEY (store_id)
    REFERENCES inventory.stores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS auth.user_stores
    ADD CONSTRAINT fk_user_store_user FOREIGN KEY (user_id)
    REFERENCES auth.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS commercial.invoices
    ADD CONSTRAINT fk_invoice_customer FOREIGN KEY (customer_id)
    REFERENCES commercial.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS commercial.invoices
    ADD CONSTRAINT fk_invoice_plan FOREIGN KEY (plan_id)
    REFERENCES commercial.plans (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS commercial.payments
    ADD CONSTRAINT fk_payment_customer FOREIGN KEY (customer_id)
    REFERENCES commercial.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS commercial.payments
    ADD CONSTRAINT fk_payment_subscription FOREIGN KEY (subscription_id)
    REFERENCES commercial.subscriptions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS commercial.subscriptions
    ADD CONSTRAINT fk_subscription_customer FOREIGN KEY (customer_id)
    REFERENCES commercial.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS commercial.subscriptions
    ADD CONSTRAINT fk_subscription_plan FOREIGN KEY (plan_id)
    REFERENCES commercial.plans (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS inventory.alerts
    ADD CONSTRAINT fk_alert_product FOREIGN KEY (product_id)
    REFERENCES inventory.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS inventory.alerts
    ADD CONSTRAINT fk_alert_store FOREIGN KEY (store_id)
    REFERENCES inventory.stores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS inventory.movements
    ADD CONSTRAINT fk_movement_product FOREIGN KEY (product_id)
    REFERENCES inventory.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_movements_product
    ON inventory.movements(product_id);


ALTER TABLE IF EXISTS inventory.movements
    ADD CONSTRAINT fk_movement_store FOREIGN KEY (store_id)
    REFERENCES inventory.stores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS inventory.products
    ADD CONSTRAINT fk_product_category FOREIGN KEY (category_id)
    REFERENCES inventory.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS inventory.stock
    ADD CONSTRAINT fk_stock_product FOREIGN KEY (product_id)
    REFERENCES inventory.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS inventory.stock
    ADD CONSTRAINT fk_stock_store FOREIGN KEY (store_id)
    REFERENCES inventory.stores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS sales.cash_shifts
    ADD CONSTRAINT fk_shift_store FOREIGN KEY (store_id)
    REFERENCES inventory.stores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS sales.pos_cart
    ADD CONSTRAINT fk_cart_product FOREIGN KEY (product_id)
    REFERENCES inventory.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS sales.pos_transactions
    ADD CONSTRAINT fk_transaction_payment_method FOREIGN KEY (payment_method_id)
    REFERENCES sales.payment_methods (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS sales.pos_transactions
    ADD CONSTRAINT fk_transaction_sale FOREIGN KEY (sale_id)
    REFERENCES sales.sales (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS sales.pos_transactions
    ADD CONSTRAINT fk_transaction_shift FOREIGN KEY (shift_id)
    REFERENCES sales.cash_shifts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS sales.sale_items
    ADD CONSTRAINT fk_sale_item_sale FOREIGN KEY (sale_id)
    REFERENCES sales.sales (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS sales.sales
    ADD CONSTRAINT fk_sale_store FOREIGN KEY (store_id)
    REFERENCES inventory.stores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;