apiVersion: v1
data:
  AI_MODEL_ENDPOINT: http://ollama.siga.svc.cluster.local:11434
  AI_MODEL_MAX_TOKENS: '1024'
  AI_MODEL_NAME: llama3
  AI_MODEL_TEMPERATURE: '0.7'
  AI_MODEL_TIMEOUT: '30'
  AUTH_SERVICE_URL: http://siga-auth.siga.svc.cluster.local:8081
  EUREKA_URL: http://siga-registry.siga.svc.cluster.local:8761/eureka
  INVENTORY_SERVICE_URL: http://siga-inventory.siga.svc.cluster.local:8082
  REDIS_HOST: siga-production-redis.ruovma.0001.use1.cache.amazonaws.com
  REDIS_PORT: '6379'
  REDIS_SSL: 'true'
  REGISTRY_SERVICE_URL: http://siga-registry.siga.svc.cluster.local:8761/eureka
  SALES_SERVICE_URL: http://siga-sales.siga.svc.cluster.local:8083
  SPRING_PROFILES_ACTIVE: eks
kind: ConfigMap
metadata:
  labels:
    app: siga-agent
    project: siga
  name: agent-config
  namespace: siga
