apiVersion: v1
data:
  DB_HOST: siga-production-postgres.crhf8ujgk6yn.us-east-1.rds.amazonaws.com
  DB_NAME: siga_auth
  DB_PORT: '5432'
  DB_SCHEMA: auth
  DB_SSL_MODE: require
  EUREKA_URL: http://siga-registry.siga.svc.cluster.local:8761/eureka
  JWT_ACCESS_EXPIRATION: '15'
  JWT_AUDIENCE: siga-gateway
  JWT_ISSUER: siga-auth
  JWT_REFRESH_EXPIRATION: '7'
  KAFKA_BOOTSTRAP_SERVERS: siga-kafka.siga.svc.cluster.local:9092
  MANAGEMENT_HEALTH_KAFKA_ENABLED: 'false'
  REDIS_HOST: siga-production-redis.nec1lg.0001.use1.cache.amazonaws.com
  REDIS_PORT: '6379'
  REDIS_SSL: 'true'
  REGISTRY_SERVICE_URL: http://siga-registry.siga.svc.cluster.local:8761/eureka
  SPRING_DATASOURCE_URL: jdbc:postgresql://siga-production-postgres.crhf8ujgk6yn.us-east-1.rds.amazonaws.com:5432/siga_auth?sslmode=require
  SPRING_PROFILES_ACTIVE: eks
kind: ConfigMap
metadata:
  labels:
    app: siga-auth
    project: siga
  name: auth-config
  namespace: siga
