package com.siga.inventory.entity

/**
 * Types of stock movements (Kardex).
 * Each movement records a change in product quantity at a specific store.
 */
enum class MovementType {
    IN,
    OUT,
    SALE,
    ADJUSTMENT,
    TRANSFER,
    RECONCILIATION
}

/**
 * Types of alerts automatically generated by the system.
 */
enum class AlertType {
    LOW_STOCK,
    OUT_OF_STOCK,
    HIGH_SALES,
    SUSPICIOUS_MOVEMENT
}
