server:
  port: 8082

spring:
  application:
    name: siga-inventory
  datasource:
    url: jdbc:postgresql://${DB_HOST:-localhost}:5432/${INVENTORY_DB_NAME:-siga_db}
    username: ${INVENTORY_DB_USER:-admin}
    password: ${INVENTORY_DB_PASSWORD:-password123}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: inventory

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:-http://localhost:8761/eureka/}

# Security OAuth2 Resource Server for JWT Pass-through
spring.security.oauth2.resourceserver.jwt.issuer-uri: "siga-auth"
