apiVersion: v1
kind: Service
metadata:
  name: siga-agent
  namespace: siga
  labels:
    app: siga-agent
    project: siga
    tier: backend
spec:
  selector:
    app: siga-agent
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
      name: http
  type: ClusterIP
