apiVersion: v1
kind: Service
metadata:
  name: siga-billing
  namespace: siga
  labels:
    app: siga-billing
    project: siga
    tier: backend
spec:
  selector:
    app: siga-billing
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      name: http
  type: ClusterIP
