apiVersion: v1
kind: Service
metadata:
  name: siga-inventory
  namespace: siga
  labels:
    app: siga-inventory
    project: siga
    tier: backend
spec:
  selector:
    app: siga-inventory
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      name: http
  type: ClusterIP
