apiVersion: v1
kind: Service
metadata:
  name: siga-registry
  namespace: siga
  labels:
    app: siga-registry
    project: siga
    tier: infrastructure
spec:
  selector:
    app: siga-registry
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      name: http
  type: ClusterIP
