# =============================================================================
# SERVICE: Grafana
# SECCIÓN: Exposición de Grafana vía LoadBalancer para la defensa
# =============================================================================
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: siga
  labels:
    app: grafana
    component: monitoring
    project: siga
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "clb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  selector:
    app: grafana
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
