# =============================================================================
# SERVICE: Prometheus
# SECCIÓN: Exposición de Prometheus vía LoadBalancer para métricas
# =============================================================================
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: siga
  labels:
    app: prometheus
    component: monitoring
    project: siga
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "clb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer
