server:
  port: 8082

spring:
  application:
    name: siga-inventario
  datasource:
    url: jdbc:postgresql://${DB_HOST:-localhost}:5432/siga_db
    username: admin
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: siga_comercial

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:-localhost}:8761/eureka/

# Security OAuth2 Resource Server for JWT Pass-through
spring.security.oauth2.resourceserver.jwt.issuer-uri: "siga-auth"
